In [1]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [5]:
a = np.floor(10 * np.random.random((3, 4)))
print(a)
print('---------')
print(a.ravel())
print('---------')
a.shape = (6, 2)
print(a)
print('---------')
print(a.T)

[[4. 4. 1. 4.]
 [8. 8. 7. 1.]
 [6. 5. 2. 5.]]
---------
[4. 4. 1. 4. 8. 8. 7. 1. 6. 5. 2. 5.]
---------
[[4. 4.]
 [1. 4.]
 [8. 8.]
 [7. 1.]
 [6. 5.]
 [2. 5.]]
---------
[[4. 1. 8. 7. 6. 2.]
 [4. 4. 8. 1. 5. 5.]]


In [23]:
import numpy as np

np.random.seed(1)
a = np.floor(10 * np.random.random((2, 2)))
b = np.floor(10 * np.random.random((2, 2)))
print(a)
print('---------')
print(b)
print('---------')
print(np.hstack((a, b)))
print(np.vstack((a, b)))

[[4. 7.]
 [0. 3.]]
---------
[[1. 0.]
 [1. 3.]]
---------
[[4. 7. 1. 0.]
 [0. 3. 1. 3.]]
[[4. 7.]
 [0. 3.]
 [1. 0.]
 [1. 3.]]


In [29]:
np.random.seed(1)
a = np.floor(10 * np.random.random((2, 12)))
print(a)
print('---')
print(np.hsplit(a, 3))
print(np.vsplit(a, 2))

[[4. 7. 0. 3. 1. 0. 1. 3. 3. 5. 4. 6.]
 [2. 8. 0. 6. 4. 5. 1. 1. 8. 9. 3. 6.]]
---
[array([[4., 7., 0., 3.],
       [2., 8., 0., 6.]]), array([[1., 0., 1., 3.],
       [4., 5., 1., 1.]]), array([[3., 5., 4., 6.],
       [8., 9., 3., 6.]])]
[array([[4., 7., 0., 3., 1., 0., 1., 3., 3., 5., 4., 6.]]), array([[2., 8., 0., 6., 4., 5., 1., 1., 8., 9., 3., 6.]])]


In [31]:
np.random.seed(1)
a = np.floor(10 * np.random.random((2, 12)))
print(a)
print('---')
print(np.hsplit(a, (3, 4, 6, 7))) # split a after third, fourth, sixth and seventh column



[[4. 7. 0. 3. 1. 0. 1. 3. 3. 5. 4. 6.]
 [2. 8. 0. 6. 4. 5. 1. 1. 8. 9. 3. 6.]]
---
[array([[4., 7., 0.],
       [2., 8., 0.]]), array([[3.],
       [6.]]), array([[1., 0.],
       [4., 5.]]), array([[1.],
       [1.]]), array([[3., 3., 5., 4., 6.],
       [1., 8., 9., 3., 6.]])]


In [37]:
a = np.arange(12)
b = a
print(b is a)
b.shape = 3, 4
print(a.shape)
print(id(a))
print(id(b))

True
(3, 4)
1340642962864
1340642962864


In [41]:
c = a.view()
print(c is a)
c.shape = 2, 6
print(c)
print(a.shape)
c[0, 4] = 1234
print(c)
print(a)



False
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(3, 4)
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [43]:
d = a.copy()
print(d is a)
d[0, 0] = 9999
print(d)
print(a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [49]:
a = np.arange(0, 40, 10).reshape(1, 4)
print(a)
print(a.shape)
b = np.tile(a, (3, 5))
print(b)
print(b.shape)

[[ 0 10 20 30]]
(1, 4)
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]
(3, 20)
