In [1]:
import numpy as np
B = np.arange(3)
print(B)
print(np.sqrt(B))

[0 1 2]
[0.         1.         1.41421356]


In [3]:
a = np.floor(10*np.random.random((3,4)))
print(a)

a.shape
# flatten the array
print(a.ravel())
a.shape = (6, 2)
print(a)
#print a.T
print(a.resize((2,6)))
print(a)

[[8. 9. 2. 9.]
 [5. 7. 6. 3.]
 [4. 3. 2. 3.]]
[8. 9. 2. 9. 5. 7. 6. 3. 4. 3. 2. 3.]
[[8. 9.]
 [2. 9.]
 [5. 7.]
 [6. 3.]
 [4. 3.]
 [2. 3.]]
None
[[8. 9. 2. 9. 5. 7.]
 [6. 3. 4. 3. 2. 3.]]


In [2]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('---')
print(b)
print('---')
print(np.hstack((a,b)))
np.hstack((a,b))

[[7. 6.]
 [7. 4.]]
---
[[2. 2.]
 [8. 3.]]
---
[[7. 6. 2. 2.]
 [7. 4. 8. 3.]]


array([[7., 6., 2., 2.],
       [7., 4., 8., 3.]])

In [4]:
a = np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a,3))
print(np.hsplit(a,(3,4)))  # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print(a)
np.vsplit(a,3)

[[5. 8. 4. 4. 7. 6. 7. 4. 3. 6. 5. 4.]
 [6. 7. 9. 0. 1. 5. 2. 1. 5. 9. 9. 5.]]
[array([[5., 8., 4., 4.],
       [6., 7., 9., 0.]]), array([[7., 6., 7., 4.],
       [1., 5., 2., 1.]]), array([[3., 6., 5., 4.],
       [5., 9., 9., 5.]])]
[array([[5., 8., 4.],
       [6., 7., 9.]]), array([[4.],
       [0.]]), array([[7., 6., 7., 4., 3., 6., 5., 4.],
       [1., 5., 2., 1., 5., 9., 9., 5.]])]
[[1. 3.]
 [6. 1.]
 [3. 9.]
 [6. 6.]
 [8. 3.]
 [4. 4.]
 [5. 4.]
 [4. 7.]
 [4. 1.]
 [6. 9.]
 [6. 1.]
 [5. 1.]]


[array([[1., 3.],
        [6., 1.],
        [3., 9.],
        [6., 6.]]),
 array([[8., 3.],
        [4., 4.],
        [5., 4.],
        [4., 7.]]),
 array([[4., 1.],
        [6., 9.],
        [6., 1.],
        [5., 1.]])]

In [6]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
b is a
b.shape = 3,4
print(a.shape)
print(id(a))
print(id(b))

(3, 4)
2052669563984
2052669563984


In [7]:
#The view method creates a new array object that looks at the same data.
c = a.view()
c is a
c.shape = 2,6
#print a.shape
c[0,4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [8]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
d is a
d[0,0] = 9999
print(d)
print(a)

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
