In [1]:
import numpy as np

vector = np.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [2]:
vector = np.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [3]:
vector = np.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [6]:
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
second_column_25 = matrix[:, 1] == 25
print(second_column_25)
matrix[second_column_25, 1] = 10
print(matrix)

[False  True False]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [9]:
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
second_column_25 = matrix == 25
print(second_column_25)
matrix[second_column_25] = 2000
print(matrix)


[[False False False]
 [False  True False]
 [False False False]]
[[   5   10   15]
 [  20 2000   30]
 [  35   40   45]]


In [13]:
vector = np.array(['1', '2', '3'])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)
vector = vector.astype(int)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]
int32
[1 2 3]


In [16]:
vector = np.array([5, 10, 15, 20])
print(vector.min())
print(vector.max())

5
20


In [19]:
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
print(matrix.sum())
print(matrix.sum(axis = 1))
print(matrix.sum(axis = 0))

225
[ 30  75 120]
[60 75 90]


In [36]:
world_alcohol = np.genfromtxt('data/world_alcohol.txt', delimiter = ',', dtype = np.float)
#print(world_alcohol)
is_value_empty = np.isnan(world_alcohol[:, 4])
#print(is_value_empty)
world_alcohol[is_value_empty, 4] = '0'
print(world_alcohol)
alcohol_consumption = world_alcohol[:, 4]
alcohol_consumption = alcohol_consumption.astype(float)
print(alcohol_consumption)
total_alcohol = alcohol_consumption.sum()
print(total_alcohol)
average_alcohol = alcohol_consumption.mean()
print(average_alcohol)


[[      nan       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.987e+03       nan       nan       nan 7.500e-01]
 [1.989e+03       nan       nan       nan 1.500e+00]
 [1.985e+03       nan       nan       nan 3.100e-01]]
[0.000e+00 0.000e+00 5.000e-01 1.620e+00 4.270e+00 1.980e+00 0.000e+00
 1.300e-01 3.900e-01 1.550e+00 6.100e+00 2.000e-01 6.200e-01 0.000e+00
 0.000e+00 5.000e-02 7.000e-02 6.000e-02 2.230e+00 1.620e+00 1.080e+00
 0.000e+00 4.510e+00 2.670e+00 4.400e-01 0.000e+00 0.000e+00 1.360e+00
 2.220e+00 1.100e-01 0.000e+00 4.480e+00 0.000e+00 1.600e+00 0.000e+00
 8.000e-01 2.240e+00 7.000e-02 3.040e+00 0.000e+00 1.000e-02 1.900e+00
 6.820e+00 3.060e+00 3.000e-02 0.000e+00 1.900e-01 2.260e+00 4.000e-02
 7.000e-01 1.490e+00 3.000e-01 3.880e+00 0.000e+00 0.000e+00 1.810e+00
 4.000e-02 0.000e+00 5.100e+00 0.000e+00 0.000e+00 0.000e+00 8.000e-02
 0.000e+00 0.000e+00 1.260e+00 0.000e

c:\Users\haora\.conda\envs\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [44]:
import numpy as np
print(np.arange(15))
a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.dtype.name)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
15
int32
int32


In [46]:
a = np.zeros((3, 4))
print(a)
b = np.zeros((2, 3, 4), dtype = np.int32)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [51]:
a = np.arange(10, 30, 5)
b = np.arange(12).reshape(3, 4)
print(a)
print(b)

[10 15 20 25]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
np.random.random((2, 3))

3.141592653589793


In [54]:
from numpy import pi
print(pi)
np.linspace(0, 2 * pi, 100)

3.141592653589793


array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [58]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
c = c - 1
print(c)
print(b ** 2)
print(a < 35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[19 28 37 46]
[0 1 4 9]
[ True  True False False]


In [63]:
# The matrix product can be performed using the dot function or method
A = np.array([
    [1, 1],
    [0, 1]
])
B = np.array([
    [2, 0],
    [3, 4]
])
print(A)
print('--------')
print(B)
print('--------')
print(A * B)
print('--------')
print(A.dot(B))
print('--------')
print(np.dot(A, B))


[[1 1]
 [0 1]]
--------
[[2 0]
 [3 4]]
--------
[[2 0]
 [0 4]]
--------
[[5 4]
 [3 4]]
--------
[[5 4]
 [3 4]]


In [77]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3]).reshape(3, 1)
print(np.dot(a, b))
print(np.dot(1, 2))
print(np.dot(a, 2))
c = np.random.randint(0, 10, (2, 3, 4))
d = np.random.randint(0, 5, (2, 4, 6))
print(np.dot(c, d).shape)
e = np.arange(1, 101).reshape(10, 10)
f = np.arange(1, 11)
print(e)
print(f)
print(np.dot(e, f))

[14]
2
[2 4 6]
(2, 3, 2, 6)
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 385  935 1485 2035 2585 3135 3685 4235 4785 5335]
